#   Columns for material classification in AVZ
avz_chemie_ktxt = (
    'Dichtmasse',
    'Dichtstoff',
    'Klebstoff',
    'Booster-Paste',
    'Kunststoff-Sicherung',
    'MAXOLEN',
    'Altemp Q NB 50',
    'Montagefett',
    'Schmierfett',
    'Sika Aktivator',
    'Sika Primer'
)
avz_norm_ktxt = (
    'Brandschutzanforderung',
    'Fire protection requirement'
)

avz_fit_ktxt = (
    'Aluminiumklebeband',
    'Bandagenausgleich',
    'Befestigungsanker',
    'Beilage',
    'Blindniet',
    'Blindnietmutter',
    'Carrosserie Scheibe o Fase',
    'Compact Verschraubung',
    'Dehnhuelse',
    'Dicht-Blindniet POP',
    'Dichtungsscheibe',
    'Distanzscheibe',
    'Drehzapfen',
    'Einpressmutter',
    'Filz schwarz',
    'Flache Scheibe',
    'Flachrundschraube',
    'Gegenmutter',
    'Gegenstueck Clip-on',
    'Gewindeeinsatz',
    'Gewindekappe',
    'Gewindestift',
    'Huelse zu Schlauchhalter',
    'Kabelbinder',
    'Kabelbindersockel',
    'Kabeldurchfuehrung',
    'Kabelverschraubung Progress',
    'Kaefigmutter KLIPKO',
    'Kantenschutzprofil',
    'Keilsicherungsscheibe',
    'Kunststoff-Schnellverschr',
    'Klebeband',
    'Linsen-Blechschraube',
    'Linsen-Flanschkopf Schraube',
    'Linsenschraube',
    'Nutenstein',
    'O-Ring',
    'Reduktion',
    'Rippenscheibe',
    'ROHRflex Wellschlauch',
    'Rohrschelle',
    'Scheibe fuer Spannzeuge',
    'Scheibe o Fase',
    'Scheibe stark',
    'Schlauchhalter',
    'Schraubenlose Endklammer',
    'Schutzschlauch',
    'Sechskantmutter',
    'Sechskantschraube',
    'Senkschraube',
    'Senk-Spanplattenschraube',
    'Sicherungsmutter',
    'Spannscheibe',
    'Spanplattenschraube',
    'Stiftschraube',
    'Stuetzring',
    'Unterlagscheibe',
    'Verbindungsschraube',
    'Verschlussschraube',
    'Verschlussstopfen',
    'Zylinderschraube',
    'Zylinderstift',
    'Sicherungsscheibe',
    'Sicherungsscheibe'
)
