#   Columns for material classification in AVZ
avz_chemie_ktxt = (
    'Dichtmasse',
    'Dichtstoff',
    'Klebstoff',
    'Booster-Paste',
    'Kunststoff-Sicherung',
    'MAXOLEN',
    'Altemp Q NB 50',
    'Montagefett',
    'Schmierfett',
    'Sika Aktivator',
    'Sika Primer'
)
avz_norm_ktxt = (
    'Brandschutzanforderung',
    'Fire protection requirement'
)

avz_fit_ktxt = (
    'Aluminiumklebeband',
    'Bandagenausgleich',
    'Befestigungsanker',
    'Beilage',
    'Blindniet',
    'Blindnietmutter',
    'Carrosserie Scheibe o Fase',
    'Compact Verschraubung',
    'Dehnhuelse',
    'Dicht-Blindniet POP',
    'Dichtungsscheibe',
    'Distanzscheibe',
    'Drehzapfen',
    'Einpressmutter',
    'Filz schwarz',
    'Flache Scheibe',
    'Flachrundschraube',
    'Gegenmutter',
    'Gegenstueck Clip-on',
    'Gewindeeinsatz',
    'Gewindekappe',
    'Gewindestift',
    'Huelse zu Schlauchhalter',
    'Kabelbinder',
    'Kabelbindersockel',
    'Kabeldurchfuehrung',
    'Kabelverschraubung Progress',
    'Kaefigmutter KLIPKO',
    'Kantenschutzprofil',
    'Keilsicherungsscheibe',
    'Kunststoff-Schnellverschr',
    'Klebeband',
    'Linsen-Blechschraube',
    'Linsen-Flanschkopf Schraube',
    'Linsenschraube',
    'Nutenstein',
    'O-Ring',
    'Reduktion',
    'Rippenscheibe',
    'ROHRflex Wellschlauch',
    'Rohrschelle',
    'Scheibe fuer Spannzeuge',
    'Scheibe o Fase',
    'Scheibe stark',
    'Schlauchhalter',
    'Schraubenlose Endklammer',
    'Schutzschlauch',
    'Sechskantmutter',
    'Sechskantschraube',
    'Senkschraube',
    'Senk-Spanplattenschraube',
    'Sicherungsmutter',
    'Spannscheibe',
    'Spanplattenschraube',
    'Stiftschraube',
    'Stuetzring',
    'Unterlagscheibe',
    'Verbindungsschraube',
    'Verschlussschraube',
    'Verschlussstopfen',
    'Zylinderschraube',
    'Zylinderstift',
    'Sicherungsscheibe',
    'Sicherungsscheibe'
)

material_list_nrc_ktxt = (
    'kosten',
    'muster'
    'dienstleistung',
    'mehrleistungen',
    'abnahmepruefzeugnis',
    'datenblatt',
    'RAM',
    'dokumentation',
    'transport',
    'zuschlag',
    'stunden',
    'brandschutzanforderung',
    'schulung',
    'AR00'
)

din_avz_test_list_raw = (
    '', '_Allgemein', '_Brandschutz', '_Dokumentation', 'A A Fahrzeug komplett', 'B A Fahrzeugkasten',
    'B B Untergestell', 'B C Laengswaende', 'B D Dach', 'B E Fahrzeugkopf', 'B F Stirnwaende',
    'B G Anschweissteile, Anbauteile', 'C A Fahrzeugausbau', 'C B Fenster', 'C C Fussboden',
    'C D Innenverkleidung', 'C E Trennwaende', 'C F Aussenanbauten', 'C G Fahrzeuglackierung', 'C H Isolierung',
    'D A Fahrzeuginneneinrichtung', 'D B Haltestangen, Griffe (Innenbereich)', 'D C Sitze, Liegen, Tische',
    'D D Sanitaereinrichtungen', 'D E Gepaeckablagen', 'D F Zusaetzliche Einrichtungen', 'E A Fahrwerk',
    'E B tragende Strukturen', 'E C Radsystem', 'E D Federung, Daempfung, Ausgleich', 'E F Anlenkungssysteme',
    'E G Schutzanbauteile', 'F A Energieanlage, Antriebsanlage', 'F B Energiezufuehrung', 'F C Energieerzeugung',
    'F D Energieumsetzung', 'G C Steuerung fuer Fahren und Bremsen', 'G F Steuerung für Energiespeicherung',
    'H A Hilfsbetriebsanlagen', 'H C Batterieeinrichtung', 'H E Kuehlung fuer Energie- und Antriebsanlage',
    'J A Ueberwachungs- und Sicherheitseinrichtungen', 'J D Sicherheitseinrichtungen',
    'J E Datenuebertragungseinrichtungen', 'J G Zusaetzliche Ausstattungen', 'K A Beleuchtung',
    'K B Aussenbeleuchtungseinrichtungen', 'K C Innenbeleuchtungseinrichtungen', 'L A Klimatisierung',
    'L D Verteilung', 'M B Sanden', 'M C Schmiereinrichtung', 'M D Weichensteuerung', 'N A Tueren, Einstiege',
    'N B Aussentueren', 'N C Innentueren', 'N D Einstiege, Aufstiege (nicht innen)', 'N E Behinderteneinstiege',
    'P A Informationseinrichtungen', 'P B optische Informationseinrichtungen',
    'P F akustische Informationseinrichtungen', 'Q A Pneumatik / Hydraulik', 'Q B Erzeugung',
    'Q D Bevorratung', 'Q E Verteilung', 'R A Bremse', 'R B Bremselemente', 'S A Fahrzeugverbindungseinrichtungen',
    'S D Stosseinrichtungen, Puffereinrichtungen', 'S F Uebergaenge / Uebergangseinrichtungen',
    'T A Tragsysteme, Umschliessungen', 'T B Schraenke, Behaelter, Container', 'T C Gerueste, Tafeln',
    'T D Bedien- und Anzeigeeinheiten', 'T E Elektronische Aufbausysteme', 'U A Elektrische Leitungsverlegung',
    'U B Kabel, Leitungen und Schienen', 'U C Bezeichnungs- und Anschlussmaterial', 'U D Verbindungsmaterial',
    'U E Durchfuehrungen', 'U F Leitungskanaele, -rohre, -schlaeuche'
)

din_avz_test_list_processed = (
    ['_', 'not_assigned'], ['_', '_Allgemein'], ['_', '_Brandschutz'], ['_', '_Dokumentation'],
    ['AA', 'Fahrzeug komplett'], ['BA', 'Fahrzeugkasten'], ['BB', 'Untergestell'], ['BC', 'Laengswaende'],
    ['BD', 'Dach'], ['BE', 'Fahrzeugkopf'], ['BF', 'Stirnwaende'], ['BG', 'Anschweissteile, Anbauteile'],
    ['CA', 'Fahrzeugausbau'], ['CB', 'Fenster'], ['CC', 'Fussboden'], ['CD', 'Innenverkleidung'], ['CE', 'Trennwaende'],
    ['CF', 'Aussenanbauten'], ['CG', 'Fahrzeuglackierung'], ['CH', 'Isolierung'], ['DA', 'Fahrzeuginneneinrichtung'],
    ['DB', 'Haltestangen, Griffe (Innenbereich)'], ['DC', 'Sitze, Liegen, Tische'], ['DD', 'Sanitaereinrichtungen'],
    ['DE', 'Gepaeckablagen'], ['DF', 'Zusaetzliche Einrichtungen'], ['EA', 'Fahrwerk'], ['EB', 'tragende Strukturen'],
    ['EC', 'Radsystem'], ['ED', 'Federung, Daempfung, Ausgleich'], ['EF', 'Anlenkungssysteme'],
    ['EG', 'Schutzanbauteile'],
    ['FA', 'Energieanlage, Antriebsanlage'], ['FB', 'Energiezufuehrung'], ['FC', 'Energieerzeugung'],
    ['FD', 'Energieumsetzung'], ['GC', 'Steuerung fuer Fahren und Bremsen'], ['GF', 'Steuerung für Energiespeicherung'],
    ['HA', 'Hilfsbetriebsanlagen'], ['HC', 'Batterieeinrichtung'], ['HE', 'Kuehlung fuer Energie- und Antriebsanlage'],
    ['JA', 'Ueberwachungs- und Sicherheitseinrichtungen'], ['JD', 'Sicherheitseinrichtungen'],
    ['JE', 'Datenuebertragungseinrichtungen'], ['JG', 'Zusaetzliche Ausstattungen'], ['KA', 'Beleuchtung'],
    ['KB', 'Aussenbeleuchtungseinrichtungen'], ['KC', 'Innenbeleuchtungseinrichtungen'], ['LA', 'Klimatisierung'],
    ['LD', 'Verteilung'], ['MB', 'Sanden'], ['MC', 'Schmiereinrichtung'], ['MD', 'Weichensteuerung'],
    ['NA', 'Tueren, Einstiege'], ['NB', 'Aussentueren'], ['NC', 'Innentueren'],
    ['ND', 'Einstiege, Aufstiege (nicht innen)'], ['NE', 'Behinderteneinstiege'], ['PA', 'Informationseinrichtungen'],
    ['PB', 'optische Informationseinrichtungen'], ['PF', 'akustische Informationseinrichtungen'],
    ['QA', 'Pneumatik / Hydraulik'], ['QB', 'Erzeugung'], ['QD', 'Bevorratung'], ['QE', 'Verteilung'], ['RA', 'Bremse'],
    ['RB', 'Bremselemente'], ['SA', 'Fahrzeugverbindungseinrichtungen'],
    ['SD', 'Stosseinrichtungen, Puffereinrichtungen'],
    ['SF', 'Uebergaenge / Uebergangseinrichtungen'], ['TA', 'Tragsysteme, Umschliessungen'],
    ['TB', 'Schraenke, Behaelter, Container'], ['TC', 'Gerueste, Tafeln'], ['TD', 'Bedien- und Anzeigeeinheiten'],
    ['TE', 'Elektronische Aufbausysteme'], ['UA', 'Elektrische Leitungsverlegung'],
    ['UB', 'Kabel, Leitungen und Schienen'],
    ['UC', 'Bezeichnungs- und Anschlussmaterial'], ['UD', 'Verbindungsmaterial'], ['UE', 'Durchfuehrungen'],
    ['UF', 'Leitungskanaele, -rohre, -schlaeuche']
)
