#   Columns for material classification in AVZ

chemie_ktxt_excluded = ['blech', 'abdeck']

chemie_ktxt = (
    '41233 rw',
    '2k-pu-lack',
    '2k-ep grundierung',
    'alexit',
    'aqua füller',
    'antirutschbeschichtung',
    'altemp',
    'antifrogen',
    'bahnspachtel ',
    'basecoat',
    'berucoat',
    'booster-paste',
    'brandschutzmasse',
    'cleaning agent',
    'cab-o-sil',
    'decklack',
    'dichtmasse',
    'dichtstoff',
    'eisenglimmer',
    'epoxy',
    'ecorail',
    'farba',
    'fettspray',
    'fugenmasse',
    'getriebeoel',
    'haerter ',
    'härter',
    'hardener',
    'harter',
    'hydraulik oel',
    'hydraulikoel',
    'igp-dura',
    'igp-korroprimer',
    'klebstoff',
    'maxolen',
    'mehrzweckfett',
    'montagefett',
    'nextel-suede',
    'nuvovern',
    'printjet cleaner',
    'pur31',
    'pur 31',
    'podkład wypełniający',
    'reiniger',
    'reparaturlack',
    'rozcienczalnik',
    'remoplast',
    'rem pur',
    'rem 2k',
    'schmierfett',
    'schmiermittel',
    'schwingungsdaempfungsstoff',
    'senepol',
    'senopox',
    'senopur',
    'senorail',
    'senosol',
    'sika',
    'silicon remover',
    'teroson',
    'thinner',
    'universalgrund',
    'utwardzacz',
    'verduenner',
    'verduner',
    'verduennung')

outsourcing_companies_excluded = ['uziem', 'erdung']
outsourcing_companies_dict = {
    "L504132": "Aidal Sp. z o.o.",
    "L501633": "CH&CH sp. z o.o.",
    "L503749": "Chmielak & Chomicki Sp. z o.o.",
    "L500791": "DEKRA Praca sp. z o.o.",
    "L503825": "Electraza",
    "590427": "ELTOM",
    "L501499": "ELTOM  T.Kulicki Sp. K.",
    "591539": "KORONTO Sp. z o.o.",
    "L501227": "KORONTO Sp. z o.o.",
    "L500944": "Mundo Enterprise",
    "L500958": "POLPRO",
    "L503821": "PROMOTOR EU Sp. z o.o.",
    "L500655": "WAGI-STAL P.P.H.U. s.c.",
    #"L500946": "Stanisław Gurba Firma Handlowo-Usługowa", # dostarcza głównie materiał - nie usuwać pozycji z matlist; ryzyko braku
    #"PHU Creative _ Marcin Antoniak", # jakiś dostawca siedlecki materiału
}

outsourcing_ktxt_excluded = []
outsourcing_ktxt = (
    "cięcie",
    "ciecie",
    "formatki",
    "konwój pojazdu",
    'mycie',
    "montaż",
    "nakładanie",
    "naprawa",
    "obciążenie",
    "okablowanie",
    'oklablowanie',
    "położenie",
    "przejścia",
    "przewijanie",
    "przewinięcie",
    "przewody",
    "przygotowanie",
    "rozliczenie",
    "składanie",
    "spawani",
    "szablon",
    "testowanie",
    "usługa",
    "usluga",
    "uzbrajanie",
    "wiązki",
    "wprowadzenie",
    "wydruk",
    "wyk.",
    "wykonanie",
    "wykonywanie",
    "wiercenie",
    "zabezpieczenie",
    "zarabianie",
    "zdejmowanie",
    "zdjęcie",
    "zestaw setów"
    #"test" - cześć wspólna wielu nazw; za dużo wyjątków
)

avz_norm_ktxt = (
    'Brandschutzanforderung',
    'Fire protection requirement',
)

avz_fit_ktxt = (
    'Aluminiumklebeband',
    'Bandagenausgleich',
    'Befestigungsanker',
    'Beilage',
    'Blindniet',
    'Blindnietmutter',
    'Carrosserie Scheibe o Fase',
    'Compact Verschraubung',
    'Dehnhuelse',
    'Dicht-Blindniet POP',
    'Dichtungsscheibe',
    'Distanzscheibe',
    'Drehzapfen',
    'Einpressmutter',
    'Filz schwarz',
    'Flache Scheibe',
    'Flachrundschraube',
    'Gegenmutter',
    'Gegenstueck Clip-on',
    'Gewindeeinsatz',
    'Gewindekappe',
    'Gewindestift',
    'Huelse zu Schlauchhalter',
    'Kabelbinder',
    'Kabelbindersockel',
    'Kabeldurchfuehrung',
    'Kabelverschraubung Progress',
    'Kaefigmutter KLIPKO',
    'Kantenschutzprofil',
    'Keilsicherungsscheibe',
    'Kunststoff-Schnellverschr',
    'Klebeband',
    'Linsen-Blechschraube',
    'Linsen-Flanschkopf Schraube',
    'Linsenschraube',
    'Nutenstein',
    'O-Ring',
    'Reduktion',
    'Rippenscheibe',
    'ROHRflex Wellschlauch',
    'Rohrschelle',
    'Scheibe fuer Spannzeuge',
    'Scheibe o Fase',
    'Scheibe stark',
    'Schlauchhalter',
    'Schraubenlose Endklammer',
    'Schutzschlauch',
    'Sechskantmutter',
    'Sechskantschraube',
    'Senkschraube',
    'Senk-Spanplattenschraube',
    'Sicherungsmutter',
    'Spannscheibe',
    'Spanplattenschraube',
    'Stiftschraube',
    'Stuetzring',
    'Unterlagscheibe',
    'Verbindungsschraube',
    'Verschlussschraube',
    'Verschlussstopfen',
    'Zylinderschraube',
    'Zylinderstift',
    'Sicherungsscheibe',
    'Sicherungsscheibe'
)

#Flaga mat/nrc/chemie(mat)/outsourcing(work)/services(work)
# bossard - po kol fk
# ktl/kanban - po kol fk,
# kable - po kol fk,
#oddzielne flagi BMEB/AMEB

material_list_nrc_ktxt = (
    'abnahmepruefzeugnis',
    'allgemeine',
    'AR00',
    'berechnung',
    'brandschutzanforderung',
    'commisioning',
    'commissioning',
    'certificate',
    'ceryfikat',
    'datenblatt',
    'declaration',
    'deklaracja',
    'design',
    'dienstleistung',
    'documenation',
    'documentation',
    'dokumentation',
    'einmalkosten',
    'emv zertifikat',
    'engineering',
    'emv-zertifikat',
    'erklaerung',
    'ersatzteilliste',
    'fai',
    'fire protection',
    'fire safety certificate'
    'fire safety',
    'freigabe',
    'konformität'
    'licencja',
    'lieferspezifikation',
    'lizenzen',
    'magazyn',
    'mata ochronna',
    'materiał',
    'mock-up',
    'muster',
    'nachweis',
    'opracowanie',
    'produktbezeichnungen',
    'produktgleichheit',
    'projektleitung',
    'próbka',
    'pruefprotokoll',
    'prüfablaufprotokol',
    'prüfprotokol',
    'prüfkosten',
    'piach techniczny',
    'ram lcc',
    'ram/lcc',
    'ram-lcc',
    'ram-spezifikation',
    'reisekosten',
    'opracowanie',
    'opłata',
    'schulung',
    'software',
    'stunden',
    'swiadectwo',
    'szkolenie',
    'świadectwo',
    'training',
    'tsi loc&pas',
    'tsi noi',
    'tsi prm',
    'tłumacz',
    'współpraca',
    'werkzeugskosten',
    'wykładzina',
    'zgodność',
    'support durch stag',
)

eurostat_indicator_list = (
    'C13',
    'C20',
    'C22',
    'C27',
    'C203',
    'C231',
    'C241',
    'C245',
    'C251',
    'C256',
    'C271',
    'C272',
    'C274',
    'C302',
    'C1621',
    'C2011',
    'C2219',
    'C2221',
    'C2314',
    'C2442',
    'C2444',
    'C2511',
    'C2512',
    'C2561',
    'C2562',
    'C2591',
    'C2593',
    'C2594',
    'C2711',
    'C2712',
    'C2732',
    'C2813',
    'C2815',
    'C2825',
    'C2931'
)

din_avz_test_list_raw = (
    '', '_Allgemein', '_Brandschutz', '_Dokumentation', 'A A Fahrzeug komplett', 'B A Fahrzeugkasten',
    'B B Untergestell', 'B C Laengswaende', 'B D Dach', 'B E Fahrzeugkopf', 'B F Stirnwaende',
    'B G Anschweissteile, Anbauteile', 'C A Fahrzeugausbau', 'C B Fenster', 'C C Fussboden',
    'C D Innenverkleidung', 'C E Trennwaende', 'C F Aussenanbauten', 'C G Fahrzeuglackierung', 'C H Isolierung',
    'D A Fahrzeuginneneinrichtung', 'D B Haltestangen, Griffe (Innenbereich)', 'D C Sitze, Liegen, Tische',
    'D D Sanitaereinrichtungen', 'D E Gepaeckablagen', 'D F Zusaetzliche Einrichtungen', 'E A Fahrwerk',
    'E B tragende Strukturen', 'E C Radsystem', 'E D Federung, Daempfung, Ausgleich', 'E F Anlenkungssysteme',
    'E G Schutzanbauteile', 'F A Energieanlage, Antriebsanlage', 'F B Energiezufuehrung', 'F C Energieerzeugung',
    'F D Energieumsetzung', 'G C Steuerung fuer Fahren und Bremsen', 'G F Steuerung für Energiespeicherung',
    'H A Hilfsbetriebsanlagen', 'H C Batterieeinrichtung', 'H E Kuehlung fuer Energie- und Antriebsanlage',
    'J A Ueberwachungs- und Sicherheitseinrichtungen', 'J D Sicherheitseinrichtungen',
    'J E Datenuebertragungseinrichtungen', 'J G Zusaetzliche Ausstattungen', 'K A Beleuchtung',
    'K B Aussenbeleuchtungseinrichtungen', 'K C Innenbeleuchtungseinrichtungen', 'L A Klimatisierung',
    'L D Verteilung', 'M B Sanden', 'M C Schmiereinrichtung', 'M D Weichensteuerung', 'N A Tueren, Einstiege',
    'N B Aussentueren', 'N C Innentueren', 'N D Einstiege, Aufstiege (nicht innen)', 'N E Behinderteneinstiege',
    'P A Informationseinrichtungen', 'P B optische Informationseinrichtungen',
    'P F akustische Informationseinrichtungen', 'Q A Pneumatik / Hydraulik', 'Q B Erzeugung',
    'Q D Bevorratung', 'Q E Verteilung', 'R A Bremse', 'R B Bremselemente', 'S A Fahrzeugverbindungseinrichtungen',
    'S D Stosseinrichtungen, Puffereinrichtungen', 'S F Uebergaenge / Uebergangseinrichtungen',
    'T A Tragsysteme, Umschliessungen', 'T B Schraenke, Behaelter, Container', 'T C Gerueste, Tafeln',
    'T D Bedien- und Anzeigeeinheiten', 'T E Elektronische Aufbausysteme', 'U A Elektrische Leitungsverlegung',
    'U B Kabel, Leitungen und Schienen', 'U C Bezeichnungs- und Anschlussmaterial', 'U D Verbindungsmaterial',
    'U E Durchfuehrungen', 'U F Leitungskanaele, -rohre, -schlaeuche'
)

din_avz_test_list_processed = (
    ['_', 'not_assigned'], ['_', '_Allgemein'], ['_', '_Brandschutz'], ['_', '_Dokumentation'],
    ['AA', 'Fahrzeug komplett'], ['BA', 'Fahrzeugkasten'], ['BB', 'Untergestell'], ['BC', 'Laengswaende'],
    ['BD', 'Dach'], ['BE', 'Fahrzeugkopf'], ['BF', 'Stirnwaende'], ['BG', 'Anschweissteile, Anbauteile'],
    ['CA', 'Fahrzeugausbau'], ['CB', 'Fenster'], ['CC', 'Fussboden'], ['CD', 'Innenverkleidung'], ['CE', 'Trennwaende'],
    ['CF', 'Aussenanbauten'], ['CG', 'Fahrzeuglackierung'], ['CH', 'Isolierung'], ['DA', 'Fahrzeuginneneinrichtung'],
    ['DB', 'Haltestangen, Griffe (Innenbereich)'], ['DC', 'Sitze, Liegen, Tische'], ['DD', 'Sanitaereinrichtungen'],
    ['DE', 'Gepaeckablagen'], ['DF', 'Zusaetzliche Einrichtungen'], ['EA', 'Fahrwerk'], ['EB', 'tragende Strukturen'],
    ['EC', 'Radsystem'], ['ED', 'Federung, Daempfung, Ausgleich'], ['EF', 'Anlenkungssysteme'],
    ['EG', 'Schutzanbauteile'],
    ['FA', 'Energieanlage, Antriebsanlage'], ['FB', 'Energiezufuehrung'], ['FC', 'Energieerzeugung'],
    ['FD', 'Energieumsetzung'], ['GC', 'Steuerung fuer Fahren und Bremsen'], ['GF', 'Steuerung für Energiespeicherung'],
    ['HA', 'Hilfsbetriebsanlagen'], ['HC', 'Batterieeinrichtung'], ['HE', 'Kuehlung fuer Energie- und Antriebsanlage'],
    ['JA', 'Ueberwachungs- und Sicherheitseinrichtungen'], ['JD', 'Sicherheitseinrichtungen'],
    ['JE', 'Datenuebertragungseinrichtungen'], ['JG', 'Zusaetzliche Ausstattungen'], ['KA', 'Beleuchtung'],
    ['KB', 'Aussenbeleuchtungseinrichtungen'], ['KC', 'Innenbeleuchtungseinrichtungen'], ['LA', 'Klimatisierung'],
    ['LD', 'Verteilung'], ['MB', 'Sanden'], ['MC', 'Schmiereinrichtung'], ['MD', 'Weichensteuerung'],
    ['NA', 'Tueren, Einstiege'], ['NB', 'Aussentueren'], ['NC', 'Innentueren'],
    ['ND', 'Einstiege, Aufstiege (nicht innen)'], ['NE', 'Behinderteneinstiege'], ['PA', 'Informationseinrichtungen'],
    ['PB', 'optische Informationseinrichtungen'], ['PF', 'akustische Informationseinrichtungen'],
    ['QA', 'Pneumatik / Hydraulik'], ['QB', 'Erzeugung'], ['QD', 'Bevorratung'], ['QE', 'Verteilung'], ['RA', 'Bremse'],
    ['RB', 'Bremselemente'], ['SA', 'Fahrzeugverbindungseinrichtungen'],
    ['SD', 'Stosseinrichtungen, Puffereinrichtungen'],
    ['SF', 'Uebergaenge / Uebergangseinrichtungen'], ['TA', 'Tragsysteme, Umschliessungen'],
    ['TB', 'Schraenke, Behaelter, Container'], ['TC', 'Gerueste, Tafeln'], ['TD', 'Bedien- und Anzeigeeinheiten'],
    ['TE', 'Elektronische Aufbausysteme'], ['UA', 'Elektrische Leitungsverlegung'],
    ['UB', 'Kabel, Leitungen und Schienen'],
    ['UC', 'Bezeichnungs- und Anschlussmaterial'], ['UD', 'Verbindungsmaterial'], ['UE', 'Durchfuehrungen'],
    ['UF', 'Leitungskanaele, -rohre, -schlaeuche']
)
